version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"         # 每天 UTC 时间 9:00 检查
      timezone: "Asia/Shanghai" # 时区设置
    target-branch: "dependabot"
    open-pull-requests-limit: 15  # 最大 PR 数量
    reviewers:                  # 自动添加审阅者
      - "team-lead"
    assignees:                  # 自动分配负责人
      - "maintainer"
    ignore:                    # 忽略特定依赖
      - dependency-name: "log4j:*"
        versions: [">= 3.0.0"] # 忽略 log4j 2.x 的更新
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
    commit-message:            # 自定义提交信息
      prefix: "chore"
      include: "scope"
    labels:                    # 自动添加标签
      - "dependencies"
      - "automated"
  - package-ecosystem: "maven"
    directory: "/os-dependencies"
    schedule:
      interval: "daily"
      time: "10:00"         # 每天 UTC 时间 9:00 检查
      timezone: "Asia/Shanghai" # 时区设置
    target-branch: "dependabot"
    open-pull-requests-limit: 15  # 最大 PR 数量
    reviewers:                  # 自动添加审阅者
      - "ACANX"
    assignees:                  # 自动分配负责人
      - "ACANX"
    ignore:                    # 忽略特定依赖
      - dependency-name: "log4j:*"
        versions: [">= 2.0.0"] # 忽略 log4j 2.x 的更新
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
        versions: [">= 6.0.0"] # 忽略 junit-jupiter 6.x 的更新      
      - dependency-name: "org.springframework:spring-core"
        versions: [">= 7.0.0"] # 忽略 spring-core 7.x 的更新           
      - dependency-name: "org.apache.flink:flink-clients"
      - dependency-name: "org.openjfx:javafx-base"
      - dependency-name: "org.openjfx:javafx-controls"
      - dependency-name: "org.openjfx:javafx-graphics"
      - dependency-name: "org.openjfx:javafx-fxml"
      - dependency-name: "org.openjfx:javafx-swing"
      - dependency-name: "org.openjfx:javafx-web"                         
      - dependency-name: "org.openjfx:javafx-media"             
      - dependency-name: "org.apache.hadoop:hadoop-client"                    
    commit-message:            # 自定义提交信息
      prefix: "chore"
      include: "scope"
    labels:                    # 自动添加标签
      - "依赖:升级"
      - "自动化:提交"
    pull-request-branch-name:
      separator: "-"              # 分支名使用短横线分隔
    allow:
      - dependency-type: "all"      # 允许所有依赖类型
  - package-ecosystem: "maven"
    directory: "/meta-model"
    schedule:
      interval: "daily"
      time: "10:00"         # 每天 UTC 时间 9:00 检查
      timezone: "Asia/Shanghai" # 时区设置
    target-branch: "dependabot"
    open-pull-requests-limit: 15  # 最大 PR 数量
    reviewers:                  # 自动添加审阅者
      - "team-lead"
    assignees:                  # 自动分配负责人
      - "maintainer"
    ignore:                    # 忽略特定依赖
      - dependency-name: "log4j:*"
        versions: [">= 3.0.0"] # 忽略 log4j 3.x 的更新
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
        versions: [">= 6.0.0"] # 忽略 junit-jupiter 6.x 的更新
    commit-message:            # 自定义提交信息
      prefix: "chore"
      include: "scope"
    labels:                    # 自动添加标签
      - "dependencies"
      - "automated"
  - package-ecosystem: "maven"
    directory: "/meta-component"
    schedule:
      interval: "daily"
      time: "10:00"         # 每天 UTC 时间 9:00 检查
      timezone: "Asia/Shanghai" # 时区设置
    target-branch: "dependabot"
    open-pull-requests-limit: 15  # 最大 PR 数量
    reviewers:                  # 自动添加审阅者
      - "team-lead"
    assignees:                  # 自动分配负责人
      - "maintainer"
    ignore:                    # 忽略特定依赖
      - dependency-name: "log4j:*"
        versions: [">= 3.0.0"] # 忽略 log4j 3.x 的更新
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
    commit-message:            # 自定义提交信息
      prefix: "chore(deps)"
      include: "scope"
    labels:                    # 自动添加标签
      - "dependencies"
      - "automated"